config/routes.rb
Rails.application.routes.draw do
  resources :nclientes
  resources :clientes
  #get 'home/index'
  root 'home#index'
  get 'home/pag2'
  get 'home/pag3'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ncliente.rb
class Ncliente < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def pag2
  end
  def pag3
  end
end

app/controllers/nclientes_controller.rb
class NclientesController < ApplicationController
  before_action :set_ncliente, only: %i[ show edit update destroy ]

  # GET /nclientes or /nclientes.json
  def index
    @nclientes = Ncliente.all
  end

  # GET /nclientes/1 or /nclientes/1.json
  def show
  end

  # GET /nclientes/new
  def new
    @ncliente = Ncliente.new
  end

  # GET /nclientes/1/edit
  def edit
  end

  # POST /nclientes or /nclientes.json
  def create
    @ncliente = Ncliente.new(ncliente_params)

    respond_to do |format|
      if @ncliente.save
        format.html { redirect_to ncliente_url(@ncliente), notice: "Ncliente was successfully created." }
        format.json { render :show, status: :created, location: @ncliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ncliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nclientes/1 or /nclientes/1.json
  def update
    respond_to do |format|
      if @ncliente.update(ncliente_params)
        format.html { redirect_to ncliente_url(@ncliente), notice: "Ncliente was successfully updated." }
        format.json { render :show, status: :ok, location: @ncliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ncliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nclientes/1 or /nclientes/1.json
  def destroy
    @ncliente.destroy

    respond_to do |format|
      format.html { redirect_to nclientes_url, notice: "Ncliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncliente
      @ncliente = Ncliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ncliente_params
      params.require(:ncliente).permit(:nome, :cpf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nclientes_helper.rb
module NclientesHelper
end

app/views/home/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Inscrição Academia', root_path,class:'navbar-brand'%> <!-- CÓDIGO DE LINK EM TAG RUBY-->	
    <!--<a class="navbar-brand" href="#">Inscrição Academia</a>   CÓDIGO DE LINK EM HTML-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!--<a class="nav-link" href="#">Link</a>-->
          <%= link_to 'Clientes',home_pag2_path, class: 'navbar-brand'%>
        </li>
        <li class="nav-item">
        	<%= link_to 'Modalidades',home_pag3_path,class:'navbar-brand'%>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="digite o nome ou CPF do cliente" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Procurar</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>GALERA NÓS VAMOS CONSEGUIR</h1>
<p>Para mais informações vá para o posto de saúde do seu bairro</p>

app/views/home/pag2.html.erb
<h1>Lista de clientes</h1>
<head>
	Digite seu usuário<input type="text" id ="nome" onchange="cod1()">
	Digite sua senha<input ="text" id="senha" onchange="cod2()">
	<button onclick="setTimeout(cod, 30)" style="width:50px;height:30px" tittle="Enviar">
	
	<script>
		function cod(){
			var n=0;
			function cod1(){
				if(nome=="empregado"){
					alert("Certo");
					n++;
				}else{
					alert("Errado");
					n--;
				}
			}
			function cod2(){
				if(senha=="123"){
					n++;
					alert("Certo");
				}else{
					n--;
					alert("Errado");
				}
			}
			if(n<1){
				alert("Usuário ou senha inválidos");
				history.back();
			}
		}
	</script>

		
	<!--<script>
		var nome,senha;
	alert("Página de Empregados");
	nome = prompt("Informe seu nome");
	senha = prompt("Digite sua senha");
	if(nome=="empregado" && senha=="123"){
		alert("Bem vindo ao banco de dados do sistema.");
		
	}else{
		alert("Usuário ou senha inválidos");
		history.back();
	}
	</script>-->
</head>

</body>

app/views/home/pag3.html.erb
<h1>SAIBA POR ONDE COMEÇAR</h1>
<p1>AQUI NA TOPFIT TEMOS DIVERSOS TIPOS DE MODALIDADES DE EXERCÍCIOS<br>EXERCÍCIOS DE BAIXO IMPACTO PARA INICIANTES E EXERCÍCIOS DE ALTA PERFORMANCE PARA VOCÊ QUE QUER SE DESAFIAR,CONFIRA AS MODALIDADES:</p1>
<div style="position: center">
	<p>CICLISMO</p>
	<p>CAMINHADA</p>
	<p>MUSCULAÇÃO</p>
	<p>FUNCIONAL(CROSSFIT)</p>
	<p>PILATES</p>
	<p>TAI CHI</p>
	<p>FUTEBOL</p>
	<p>VÔLEI</p>
	<p>CAPOEIRA</p>
	<p>DANÇA</p>
	<p>PING PONG</p>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>TOPFIT</title>
  </head>
  <body>
    <div class ='container'>
      <%= render 'home/nav'%>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/nclientes/_form.html.erb
<%= form_with(model: ncliente, local: true) do |form| %>
  <% if ncliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ncliente.errors.count, "error") %> prohibited this ncliente from being saved:</h2>

      <ul>
        <% ncliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nclientes/edit.html.erb
<h1>Editing Ncliente</h1>

<%= render 'form', ncliente: @ncliente %>

<%= link_to 'Show', @ncliente %> |
<%= link_to 'Back', nclientes_path %>

app/views/nclientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nclientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nclientes.each do |ncliente| %>
      <tr>
        <td><%= ncliente.nome %></td>
        <td><%= ncliente.cpf %></td>
        <td><%= link_to 'Show', ncliente %></td>
        <td><%= link_to 'Edit', edit_ncliente_path(ncliente) %></td>
        <td><%= link_to 'Destroy', ncliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ncliente', new_ncliente_path %>

app/views/nclientes/new.html.erb
<h1>New Ncliente</h1>

<%= render 'form', ncliente: @ncliente %>

<%= link_to 'Back', nclientes_path %>

app/views/nclientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ncliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @ncliente.cpf %>
</p>

<%= link_to 'Edit', edit_ncliente_path(@ncliente) %> |
<%= link_to 'Back', nclientes_path %>